name: Lint

on:
  push:
    paths:
      - packages/**
      - website/**

jobs:
  validate:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "16"
      - run: yarn install
      - run: yarn lint
